export default function Head() {
  return (
    <>
      <title>Store</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="This is my store" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
