export default function Head() {
  return (
    <>
      <title>Smallkind</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        name="As a family-run concept store, we attach great importance to sustainably manufactured children's clothing, toys and room interior."
        content="Generated by create next app"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
